# ファイル: .github/workflows/deploy.yml
name: Deploy wgconf via RSYNC

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Rsync Deploy to Web Server
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: SSH 鍵をセットアップ
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: known_hosts の登録
        run: |
          mkdir -pv "$HOME/.ssh"
          ssh-keyscan -H "${{ secrets.SERVER_HOST }}" >> "$HOME/.ssh/known_hosts"
        shell: bash

      - name: rsync で /public をデプロイ
        run: |
          rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=yes" \
            public/ \
            "${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:${{ secrets.DEPLOY_DIR }}"
        shell: bash
